import Chat from "@/components/Chat";
import { candidate } from "@/content/candidate";

export const metadata = {
  title: `Ask about ${candidate.name}`,
};

export default function ChatPage() {
  return (
    <section className="mx-auto max-w-3xl px-5 py-14 sm:py-16">
      <div className="mb-8 text-center">
        <span className="eyebrow justify-center">
          <span className="h-1.5 w-1.5 rounded-full bg-gold" /> AI Assistant
        </span>
        <h1 className="mt-3 text-3xl font-semibold tracking-tight text-brand-dark sm:text-4xl">
          Ask the AI Assistant
        </h1>
        <p className="mx-auto mt-3 max-w-xl text-ink-500">
          Instant answers about {candidate.name}&apos;s background, plans, and priorities —
          in English or Yoruba.
        </p>
      </div>

      <Chat />

      <p className="mt-4 text-center text-xs text-ink-300">
        Answers are generated by AI from the campaign&apos;s published information and may not
        cover every detail. For official enquiries, please contact the campaign.
      </p>
    </section>
  );
}
